export const MAIN = {
  SET_TECH_LIST: "SET_TECH_LIST",
  ADD_TO_TECH_LIST: "ADD_TO_TECH_LIST",
  REMOVE_FROM_TECH_LIST: "REMOVE_FROM_TECH_LIST"
};


export const AUTH = {
  LOGIN_SHOW_LOADER: 'LOGIN_SHOW_LOADER',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
};